name = "WorldOceanAtlasTools"
uuid = "04f20302-f1b9-11e8-29d9-7d841cb0a64a"
authors = ["Benoit Pasquier <pasquieb@uci.edu>"]
version = "0.2.2"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.0"

[extras]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NCDatasets"]
