name = "WorldOceanAtlasTools"
uuid = "04f20302-f1b9-11e8-29d9-7d841cb0a64a"
authors = ["Benoit Pasquier <briochemc@gmail.com>"]
version = "0.4.2"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
MetadataArrays = "49441bc9-da82-574f-b07c-a0d10dd4ac13"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
OceanGrids = "cfe838f4-859f-11e9-2ea1-df7d4e7c3537"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DataDeps = "0.7"
MetadataArrays = "0.1"
Match = "1"
NCDatasets = "0.9, 0.10"
NearestNeighbors = "0.4"
OceanGrids = "0.1, 0.2"
StatsBase = "0.32"
Unitful = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
